# Generated by Django 4.0.2 on 2022-02-17 18:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house_number', models.SmallIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'db_table': 'pets_address',
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Breed',
                'verbose_name_plural': 'Breeds',
                'db_table': 'pets_breed',
            },
        ),
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Classification',
                'verbose_name_plural': 'Classifications',
                'db_table': 'pets_classification',
            },
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Health',
                'verbose_name_plural': 'Healths',
                'db_table': 'pets_health',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('photo', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_home', models.BooleanField(default=False)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pets.address')),
                ('bread', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pets.breed')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pets.classification')),
                ('health', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pets.health')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'db_table': 'pets_pet',
            },
        ),
    ]
