# Generated by Django 4.0.2 on 2022-02-20 18:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['-id'], 'verbose_name': 'Address', 'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['-id'], 'verbose_name': 'Breed', 'verbose_name_plural': 'Breeds'},
        ),
        migrations.AlterModelOptions(
            name='classification',
            options={'ordering': ['-id'], 'verbose_name': 'Classification', 'verbose_name_plural': 'Classifications'},
        ),
        migrations.AlterModelOptions(
            name='health',
            options={'ordering': ['-id'], 'verbose_name': 'Health', 'verbose_name_plural': 'Healths'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ['-id'], 'verbose_name': 'Pet', 'verbose_name_plural': 'Pets'},
        ),
        migrations.AddField(
            model_name='pet',
            name='publication_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
